name: mosaic_method
channels:
  - bioconda
  - conda-forge
dependencies:
    - python=3.11
    - r-tidyverse
    - r-phangorn
    - r-ape
    - r-janitor
    - r-reticulate
    - r-svglite
    - r-viridis
    - bioconductor-ggtree
    - pandas=2.1.4
    - snakemake
    - lastz
    - scipy
    - matplotlib
    - scikit-learn
    - fastani
    - sqlite
    - mummer
    - biopython
    - seaborn
    - r-treedist
    - jax
    - pip
    - pip:
        - -e .
