results_dir: "/project/bacteria_mlds/results_bacillales_lacti_v3_masked_noiupac_delta1/"
taxon_csv: "/project/bacteria_mlds-data/bacillales_taxon_lacti_v3_w_clade.csv"
# always absolute if current dir
genomes_dir: "/project/bacteria_mlds-data/bacillales_genomes_v3_no_plasmid_pretreated/"
pretreatment_dir: "/project/bacteria_mlds-data/temp_genomes/"
lastz_tools_dir: "/project/bacteria_mlds/test_florian/pretreatment/tools/"
# whether to start from fasta or precomputed assembly-wise MLDs
from_f_mld: "no"
f_mlds_dir: "/cluster/CBIO/data1/fmassip/HGT/ProjectMisha/HGTnew/dating_long_distance/results/lastz/"
# General Parameters
# either complete, update, or create
database_state: "complete"
database_name: "bacillales_lacti_v3_masked_noiupac.db"
max_threads: 255
mus: 5.0e-9
muc: 6.0e-11
# change if aligner changes
delta: 0.25
cluster_name: "clade"
genome_wise_fit: "no"
# tree drawing parameter
filter_min_genomes: 0
tree_annotation: "family.gtdb"
# dont forget to change delta
aligner: "mummer"
